### ISSUE TITLE
Announcement Style is the same as Info style

### ISSUE THREAD

**Issue by jprovasnik** [learningworks/moodle-block_advnotifications#22]
There are 5 styles to choose from when setting up a notification: Info, Success, Warning, Danger, Announcement

When Announcement is selected, it is identical to Info (according to the CSS when viewing the browser tools). 

Is it possible to make "announcement" a separate class? I'd love to make it a nice purple on my site.

**Comment by zpottie** [comment]
Hey @jprovasnik 

Thanks for your submission! The plugin was made like that by design. It allows the admin of the site to create custom styling for the announcement type of alert in their theme, custom CSS/SCSS settings or additional HTML settings.

The CSS might look something like:
```CSS
.alert.alert-announcement {
    background-color: #a6c;
    color: #fff;
    border-color: #93c;
}
```

Hope that helps! 👌 

Thanks,
Zander
